"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMMAND_RESPONSE = exports.COMMAND = void 0;
exports.COMMAND = {
  CMD_HAND_SHAKE: 0x48,
  RSP_HAND_SHAKE: 0x49,
  CMD_SOLICITAR_TABELA_REGISTROS: 0x52,
  RSP_SOLICITAR_TABELA_REGISTROS: 0x53,
  CMD_SOLICITAR_SENHA_ACESSO: 0x72,
  RSP_SOLICITAR_SENHA_ACESSO: 0x73,
  CMD_SOLICITAR_LOCAL_INSTALACAO: 0x76,
  RSP_SOLICITAR_LOCAL_INSTALACAO: 0x77,
  CMD_SOLICITAR_TEMPO_MAXIMO_RETARDO: 0x68,
  RSP_SOLICITAR_TEMPO_MAXIMO_RETARDO: 0x69,
  CMD_SOLICITAR_REGRA_PADRAO: 0x56,
  RSP_SOLICITAR_REGRA_PADRAO: 0x57,
  CMD_SOLICITAR_CLASSE_AB: 0x64,
  RSP_SOLICITAR_CLASSE_AB: 0x65,
  CMD_SOLICITAR_DATA_HORA: 0x80,
  RSP_SOLICITAR_DATA_HORA: 0x81,
  CMD_SOLICITAR_VERSAO_FIRMWARE: 0x84,
  RSP_SOLICITAR_VERSAO_FIRMWARE: 0x85,
  CMD_SOLICITAR_BLOQUEIO_ITENS_LOCAIS: 0x60,
  RSP_SOLICITAR_BLOQUEIO_ITENS_LOCAIS: 0x61,
  CMD_SOLICITAR_LISTA_EVENTOS: 0x86,
  RSP_SOLICITAR_LISTA_EVENTOS: 0x87,
  CMD_SOLICITAR_REINICIO_CENTRAL: 0x90,
  RSP_SOLICITAR_REINICIO_CENTRAL: 0x91,
  CMD_ALTERAR_TEMPO_VALIDADE_HANDSHAKE: 0x92,
  RSP_ALTERAR_TEMPO_VALIDADE_HANDSHAKE: 0x93,
  CMD_SOLICITAR_LIMPEZA_PARAMETROS_ESTATICOS: 0x94,
  RSP_SOLICITAR_LIMPEZA_PARAMETROS_ESTATICOS: 0x95,
  CMD_VERIFICAR_CONEXAO_CABO_USB: 0x98,
  RSP_VERIFICAR_CONEXAO_CABO_USB: 0x99,
  CMD_ENTRAR_EM_MODO_ATUALIZACAO_FIRMWARE: 0x9a,
  RSP_ENTRAR_EM_MODO_ATUALIZACAO_FIRMWARE: 0x9b,
  CMD_GRAVAR_TABELA_REGISTROS: 0x96,
  RSP_GRAVAR_TABELA_REGISTROS: 0x97,
  CMD_GRAVAR_SENHA_ACESSO: 0x74,
  RSP_GRAVAR_SENHA_ACESSO: 0x75,
  CMD_GRAVAR_LOCAL_INSTALACAO: 0x78,
  RSP_GRAVAR_LOCAL_INSTALACAO: 0x79,
  CMD_GRAVAR_TEMPO_MAXIMO_RETARDO: 0x70,
  RSP_GRAVAR_TEMPO_MAXIMO_RETARDO: 0x71,
  CMD_GRAVAR_REGRA_PADRAO: 0x58,
  RSP_GRAVAR_REGRA_PADRAO: 0x59,
  CMD_GRAVAR_CLASSE_AB: 0x66,
  RSP_GRAVAR_CLASSE_AB: 0x67,
  CMD_GRAVAR_DATA_HORA: 0x82,
  RSP_GRAVAR_DATA_HORA: 0x83,
  CMD_GRAVAR_BLOQUEIO_ITENS_LOCAIS: 0x62,
  RSP_GRAVAR_BLOQUEIO_ITENS_LOCAIS: 0x63,
};
exports.COMMAND_RESPONSE =
  ((_a = {}),
  (_a[exports.COMMAND.CMD_HAND_SHAKE] = exports.COMMAND.RSP_HAND_SHAKE),
  (_a[exports.COMMAND.CMD_SOLICITAR_TABELA_REGISTROS] =
    exports.COMMAND.RSP_SOLICITAR_TABELA_REGISTROS),
  (_a[exports.COMMAND.CMD_SOLICITAR_SENHA_ACESSO] =
    exports.COMMAND.CMD_SOLICITAR_SENHA_ACESSO),
  (_a[exports.COMMAND.CMD_SOLICITAR_LOCAL_INSTALACAO] =
    exports.COMMAND.RSP_SOLICITAR_LOCAL_INSTALACAO),
  (_a[exports.COMMAND.CMD_SOLICITAR_TEMPO_MAXIMO_RETARDO] =
    exports.COMMAND.RSP_SOLICITAR_TEMPO_MAXIMO_RETARDO),
  (_a[exports.COMMAND.CMD_SOLICITAR_REGRA_PADRAO] =
    exports.COMMAND.RSP_SOLICITAR_REGRA_PADRAO),
  (_a[exports.COMMAND.CMD_SOLICITAR_CLASSE_AB] =
    exports.COMMAND.RSP_SOLICITAR_CLASSE_AB),
  (_a[exports.COMMAND.CMD_SOLICITAR_DATA_HORA] =
    exports.COMMAND.RSP_SOLICITAR_DATA_HORA),
  (_a[exports.COMMAND.CMD_SOLICITAR_VERSAO_FIRMWARE] =
    exports.COMMAND.RSP_SOLICITAR_VERSAO_FIRMWARE),
  (_a[exports.COMMAND.CMD_SOLICITAR_BLOQUEIO_ITENS_LOCAIS] =
    exports.COMMAND.RSP_SOLICITAR_BLOQUEIO_ITENS_LOCAIS),
  (_a[exports.COMMAND.CMD_SOLICITAR_LISTA_EVENTOS] =
    exports.COMMAND.RSP_SOLICITAR_LISTA_EVENTOS),
  (_a[exports.COMMAND.CMD_SOLICITAR_REINICIO_CENTRAL] =
    exports.COMMAND.RSP_SOLICITAR_REINICIO_CENTRAL),
  (_a[exports.COMMAND.CMD_GRAVAR_TABELA_REGISTROS] =
    exports.COMMAND.RSP_GRAVAR_TABELA_REGISTROS),
  (_a[exports.COMMAND.CMD_GRAVAR_SENHA_ACESSO] =
    exports.COMMAND.RSP_GRAVAR_SENHA_ACESSO),
  (_a[exports.COMMAND.CMD_GRAVAR_LOCAL_INSTALACAO] =
    exports.COMMAND.RSP_GRAVAR_LOCAL_INSTALACAO),
  (_a[exports.COMMAND.CMD_GRAVAR_TEMPO_MAXIMO_RETARDO] =
    exports.COMMAND.RSP_GRAVAR_TEMPO_MAXIMO_RETARDO),
  (_a[exports.COMMAND.CMD_GRAVAR_REGRA_PADRAO] =
    exports.COMMAND.RSP_GRAVAR_REGRA_PADRAO),
  (_a[exports.COMMAND.CMD_GRAVAR_CLASSE_AB] =
    exports.COMMAND.RSP_GRAVAR_CLASSE_AB),
  (_a[exports.COMMAND.CMD_GRAVAR_DATA_HORA] =
    exports.COMMAND.RSP_GRAVAR_DATA_HORA),
  (_a[exports.COMMAND.CMD_GRAVAR_BLOQUEIO_ITENS_LOCAIS] =
    exports.COMMAND.RSP_GRAVAR_BLOQUEIO_ITENS_LOCAIS),
  (_a[exports.COMMAND.CMD_ALTERAR_TEMPO_VALIDADE_HANDSHAKE] =
    exports.COMMAND.RSP_ALTERAR_TEMPO_VALIDADE_HANDSHAKE),
  (_a[exports.COMMAND.CMD_SOLICITAR_LIMPEZA_PARAMETROS_ESTATICOS] =
    exports.COMMAND.RSP_SOLICITAR_LIMPEZA_PARAMETROS_ESTATICOS),
  (_a[exports.COMMAND.CMD_VERIFICAR_CONEXAO_CABO_USB] =
    exports.COMMAND.RSP_VERIFICAR_CONEXAO_CABO_USB),
  (_a[exports.COMMAND.CMD_ENTRAR_EM_MODO_ATUALIZACAO_FIRMWARE] =
    exports.COMMAND.RSP_ENTRAR_EM_MODO_ATUALIZACAO_FIRMWARE),
  _a);
