/**
 * Criado por Livecom on 3/19/2016.
 * Contato: contato@livecom.io
 * Site: http://livecom.io
 */

var keys = {
  // Key Encryption/Decryption - CBC-AES-256  (256 bits = 32 bytes)
  cbcEnc: new Buffer.alloc(
    32,
    "62858189A531A57ABE576FC4B0785708937E57FAC0C85BE6CB94EFE8AAC18264",
    "hex"
  ),
  // Key MAC - CBC-MAC-AES-256  (256 bits = 32 bytes)
  cbcMac: new Buffer.alloc(
    32,
    "F735DD3E06002418C0C2CD3C8DA6A8B88362D4BCD5B7E19BC4B5ADF02B9AD31F",
    "hex"
  ),
  // Key MAC Encrypt-last-block - CBC-MAC-AES-256  (256 bits = 32 bytes)
  cbcMacEnc: new Buffer.alloc(
    32,
    "6B0B54ED3493DFED5131A370CCB37843EE5A70827D0297C194BA94D0A062018F",
    "hex"
  ),
};

var CONFIG = {
  PORT_REMOTE_CONNECTION: 12347,
  PORT_REMOTE_OPPERATION: 12346,
  PORT_REMOTE_OPPERATION_MULTICAST: 12345,
  IPV4_GROUP: "239.255.55.55",
  COMANDO: {},
  POSICAO: {},
  TAMANHO: {},
  RESPOSTA: {},
  NR_CENTRAIS_INTERLIGACAO_CENTRAIS: 16,
  NR_LOCAL_INSTALACAO: 22,
  NR_MAC_ADDRESS: 6,
  NR_NOME_REGRA: 15,
  NR_NOME_ZONA: 16,
  NR_LACOS: 2,
  NR_NOME_DISPOSITIVO: 15,
  CRYPTO: {
    keys: keys,
    seqNumRecvWin: 100,
  },
  TIMEOUT: {
    RESEND_MESSAGE_REMOTE_OPPERATION: 1000,
    RESEND_MESSAGE_REMOTE_CONECTION: 1000,
    WAIT_MULTICAST_RESPONSE: 10000,
    CONNECTION: 9000,
  },
};

var COMANDO = CONFIG.COMANDO;
var POSICAO = CONFIG.POSICAO;
var TAMANHO = CONFIG.TAMANHO;
var RESPOSTA = CONFIG.RESPOSTA;

POSICAO.POSICAO_MENSAGEM_COMANDO = 0x00;
TAMANHO.uint8_t = 1;
TAMANHO.uint16_t = 2;
TAMANHO.uint32_t = 4;

//COMANDOS
COMANDO.COMANDO_SINCRONIZACAO_COORDENADOR = 0x01;
COMANDO.COMANDO_ACK_SINCRONIZACAO_COORDENADOR = 0x02;
COMANDO.COMANDO_SOLICITA_NOME_CENTRAIS_INTERLIGACAO = 0x03;
COMANDO.COMANDO_ENVIA_NOME_CENTRAIS_INTERLIGACAO = 0x04;
COMANDO.COMANDO_ENVIAR_EVENTOS_INTERLIGACAO_CENTRAL_MULTICAST = 0x05;
COMANDO.COMANDO_ACK_EVENTOS_INTERLIGACAO = 0x06;
COMANDO.COMANDO_SOLICITA_STATUS_CENTRAIS_INTERLIGACAO = 0x07;
COMANDO.COMANDO_ENVIA_STATUS_CENTRAIS_INTERLIGACAO = 0x08;
COMANDO.COMANDO_ENVIAR_EVENTOS_INTERLIGACAO_CENTRAL_UNICAST = 0x09;
COMANDO.COMANDO_SOLICITA_EVENTOS_INDIVIDUAL_INTERLIGACAO_CENTRAL = 0x0a;
COMANDO.COMANDO_ENVIA_EVENTOS_INDIVIDUAL_INTERLIGACAO_CENTRAL = 0x0b;
COMANDO.COMANDO_SOLICITA_REGRAS_INTERLIGACAO_CENTRAL = 0x0c;
COMANDO.COMANDO_ENVIA_REGRAS_INTERLIGACAO_CENTRAL = 0x0d;
COMANDO.COMANDO_SOLICITA_CONTADORES_REGISTROS_INTERLIGACAO_CENTRAL = 0x0e;
COMANDO.COMANDO_ENVIA_CONTADORES_REGISTROS_INTERLIGACAO_CENTRAL = 0x0f;
COMANDO.COMANDO_SOLICITA_REGISTROS_INTERLIGACAO_CENTRAL = 0x10;
COMANDO.COMANDO_ENVIA_REGISTROS_INTERLIGACAO_CENTRAL = 0x11;
COMANDO.COMANDO_SOLICITA_EVENTOS_INICIALIZACAO_INTERLIGACAO_CENTRAL = 0x12;
COMANDO.COMANDO_ENVIA_EVENTOS_INICIALIZACAO_INTERLIGACAO_CENTRAL = 0x13;
COMANDO.COMANDO_ENVIAR_COMANDOS_INTERLIGACAO_CENTRAL = 0x14;
COMANDO.COMANDO_ACK_COMANDOS_INTERLIGACAO_CENTRAL = 0x15;
COMANDO.COMANDO_SOLICITA_CRC_REGRAS_INTERLIGACAO_CENTRAL = 0x16;
COMANDO.COMANDO_ENVIA_CRC_REGRAS_INTERLIGACAO_CENTRAL = 0x17;
COMANDO.COMANDO_SOLICITA_MAC_ADDRESS_CENTRAL = 0x18;
COMANDO.COMANDO_ENVIA_MAC_ADDRESS_CENTRAL = 0x19;
COMANDO.COMANDO_SOLICITA_ZONAS_INTERLIGACAO_CENTRAL = 0x1a;
COMANDO.COMANDO_ENVIA_ZONAS_INTERLIGACAO_CENTRAL = 0x1b;
COMANDO.COMANDO_SOLICITA_DISPOSITIVOS_INTERLIGACAO_CENTRAL = 0x1c;
COMANDO.COMANDO_ENVIA_DISPOSITIVOS_INTERLIGACAO_CENTRAL = 0x1d;
COMANDO.COMANDO_SOLICITA_CONTADORES_BLOQUEIOS_INTERLIGACAO_CENTRAL = 0x1e;
COMANDO.COMANDO_ENVIA_CONTADORES_BLOQUEIOS_INTERLIGACAO_CENTRAL = 0x1f;
COMANDO.COMANDO_SOLICITA_INFORMACOES_CENTRAL_INTERLIGACAO_CENTRAL = 0x20;
COMANDO.COMANDO_ENVIA_INFORMACOES_CENTRAL_INTERLIGACAO_CENTRAL = 0x21;
COMANDO.COMANDO_SOLICITA_LACOS_INTERLIGACAO_CENTRAL = 0x22;
COMANDO.COMANDO_ENVIA_LACOS_INTERLIGACAO_CENTRAL = 0x23;
COMANDO.COMANDO_ENVIAR_COMANDOS_BLOQUEIOS_INTERLIGACAO_CENTRAL = 0x24;
COMANDO.COMANDO_ACK_COMANDOS_BLOQUEIOS_SAIDAS_INTERLIGACAO_CENTRAL = 0x25;
COMANDO.COMANDO_ENVIAR_COMANDOS_SAIDAS_INTERLIGACAO_CENTRAL = 0x26;
COMANDO.COMANDO_ACK_COMANDOS_SAIDAS_INTERLIGACAO_CENTRAL = 0x27;

COMANDO.COMANDO_SOLICITA_CONTADORES_SAIDAS_INTERLIGACAO_CENTRAL = 0x28;
COMANDO.COMANDO_ENVIA_CONTADORES_SAIDAS_INTERLIGACAO_CENTRAL = 0x29;

COMANDO.COMANDO_SOLICITA_STATUS_INTERFACE_ETHERNET_PRE_PILOTO = 0x50;
COMANDO.COMANDO_ENVIA_STATUS_INTERFACE_ETHERNET_PRE_PILOTO = 0x51;
COMANDO.COMANDO_RECEBE_MAC_ADDRESS_INTERFACE_ETHERNET_PRE_PILOTO = 0x52;
COMANDO.COMANDO_ACK_MAC_ADDRESS_INTERFACE_ETHERNET_PRE_PILOTO = 0x53;
COMANDO.COMANDO_RECEBE_FINAL_TEST_INTERFACE_ETHERNET_PRE_PILOTO = 0x54;
COMANDO.COMANDO_ACK_FINAL_TEST_INTERFACE_ETHERNET_PRE_PILOTO = 0x55;

COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_OPERACAO_REMOTA = 0x61;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_CONFIGURACAO_REMOTA = 0x62;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_SOLICITA_MAC_ADDRESS = 0x63;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_SOLICITA_NOME_MODELO = 0x64;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_AUTENTICACAO_REMOTA = 0x65;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_AUTENTICACAO_REMOTA_RESPOSTA_SESSAO = 0x66;
COMANDO.COMANDO_COMUNICACAO_PROGRAMADOR_SESSAO_INVALIDA = 0x67;

COMANDO.COMANDO_SOLICITA_DATA_HORA_INTERLIGACAO_CENTRAL = 0x30;
COMANDO.COMANDO_ENVIA_DATA_HORA_INTERLIGACAO_CENTRAL = 0x31;

COMANDO.COMANDO_NAK_RESPOSTA_CONTADOR_INVALIDO = 0x82;

COMANDO.NAK_COMANDO_INVALIDO = 255;
COMANDO.NAK_UDP = 0x80;

//BROADCAST
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_DIA =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_MES =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_DIA + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_ANO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_MES + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_HORA =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_ANO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_MINUTO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_HORA + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_SEGUNDO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_MINUTO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_CENTRAIS_CONECTADAS =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RTC_SEGUNDO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_VERSAO_CENTRAL =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_CENTRAIS_CONECTADAS + 2;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RELEASE_CENTRAL =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_VERSAO_CENTRAL + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_REVISAO_CENTRAL =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_RELEASE_CENTRAL + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_SEC_COUNTER_SEND =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_REVISAO_CENTRAL + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_SEC_COUNTER_RECV =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_SEC_COUNTER_SEND + 2;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_IP_ADRESS_DEVICES =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_SEC_COUNTER_RECV + 2;
POSICAO.TAMANHO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_IP_ADRESS_DEVICES +
  CONFIG.NR_CENTRAIS_INTERLIGACAO_CENTRAIS * 4;

//STATUS
POSICAO.POSICAO_MENSAGEM_CONTADOR_ALARME = POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_CONTADOR_FALHA =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_ALARME + TAMANHO.uint16_t;
POSICAO.POSICAO_MENSAGEM_CONTADOR_SUPERVISAO =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_FALHA + TAMANHO.uint16_t;
POSICAO.POSICAO_MENSAGEM_CONTADOR_BLOQUEIO =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_SUPERVISAO + TAMANHO.uint16_t;
POSICAO.POSICAO_MENSAGEM_CONTADOR_REGRAS =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_BLOQUEIO + TAMANHO.uint16_t;
POSICAO.POSICAO_MENSAGEM_CONTADOR_STATUS_LED =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_REGRAS + TAMANHO.uint8_t;
POSICAO.POSICAO_MENSAGEM_CONTADOR_STATUS_LED_2 =
  POSICAO.POSICAO_MENSAGEM_CONTADOR_REGRAS + TAMANHO.uint16_t;

//LEDS
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_FONTE_OPERANDO = 0;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_FONTE_FALHA =
  POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_FONTE_OPERANDO + 1;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_CENTRAL_SILENCIADA =
  POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_FONTE_FALHA + 1;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_ALARME_GERAL =
  POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_CENTRAL_SILENCIADA + 1;
POSICAO.SHIFT_STATUS_INTERLIGACAO_SIRENE_BRIGADA =
  POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_ALARME_GERAL + 1;
POSICAO.SHIFT_STATUS_INTERLIGACAO_CENTRAL_PLACA_LACO_OPERACAO =
  POSICAO.SHIFT_STATUS_INTERLIGACAO_SIRENE_BRIGADA + 1;
POSICAO.SHIFT_STATUS_INTERLIGACAO_CENTRAL_REGRAS_TEMPORIZANDO =
  POSICAO.SHIFT_STATUS_INTERLIGACAO_CENTRAL_PLACA_LACO_OPERACAO + 2;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_SIRENE_CONTINUA = 0;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_SIRENE_PULSADA = 1;
POSICAO.SHIFT_STATUS_CENTRAL_INTERLIGACAO_SIRENE_SILENCIADA = 2;

//NOME
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_NOME_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_NOME_MODELO_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_NOME_CENTRAIS +
  CONFIG.NR_LOCAL_INSTALACAO;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_ENDERECO_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_NOME_MODELO_CENTRAIS + 1;
TAMANHO.TAMANHO_MENSAGEM_INTERLIGACAO_ENVIA_NOME_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_ENVIA_ENDERECO_CENTRAIS + 1;

//MAC
POSICAO.POSICAO_MENSAGEM_MAC_ADRESS_MAC = POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
TAMANHO.TAMANHO_MENSAGEM_MAC_ADRESS =
  POSICAO.POSICAO_MENSAGEM_MAC_ADRESS_MAC + CONFIG.NR_MAC_ADDRESS;

//EVENTO
TAMANHO.ESTRUTURA_EVENTO = 52;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_TIPO_EVENTO =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_EVENTO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_TIPO_EVENTO +
  1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_CONTADOR_EVENTO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_EVENTO +
  TAMANHO.ESTRUTURA_EVENTO;
POSICAO.TAMANHO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SOLICITA_EVENTO_CORRENTE_CONTADOR_EVENTO +
  TAMANHO.uint16_t;

//REGRAS
TAMANHO.RegraRam_t = 16;
POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_REGRA =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_NOME_REGRA =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_REGRA + TAMANHO.RegraRam_t;
POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_CRC_REGRAS =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_NOME_REGRA + CONFIG.NR_NOME_REGRA;
POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_QUANTIDADE_REGRAS =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_CRC_REGRAS + TAMANHO.uint16_t;
POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_POSICAO_REGRA =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_QUANTIDADE_REGRAS + 1;
TAMANHO.TAMANHO_MENSAGEM_REGRAS_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_POSICAO_REGRA + 1;

//RegraRam_t
POSICAO.POSICAO_REGRA_RAM_VALOR_TIMER = 5;
POSICAO.POSICAO_REGRA_RAM_NUMERO = 16;
POSICAO.POSICAO_REGRA_RAM_BLOQUEADO = 1;
POSICAO.POSICAO_REGRA_RAM_BLOQUEADO_BIT = 4;

//ZONAS
TAMANHO.ZonaRam_t = 4;
POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_ZONA =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_NOME_ZONA =
  POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_ZONA + TAMANHO.ZonaRam_t;
POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_POSICAO_ZONA =
  POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_NOME_ZONA + CONFIG.NR_NOME_ZONA;
POSICAO.TAMANHO_MENSAGEM_ZONAS_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_ZONAS_CENTRAIS_POSICAO_ZONA + 1;

//ZonaRam_t
POSICAO.POSICAO_ZONA_RAM_BLOQUEADO = 1;
POSICAO.POSICAO_ZONA_RAM_ENDERECO = 2;
POSICAO.POSICAO_ZONA_RAM_BLOQUEADO_BIT = 0;

//DISPOSITIVO
TAMANHO.DispositivoRam_t = 8;
POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_DISPOSITIVO =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_NOME_DISPOSTIVO =
  POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_DISPOSITIVO +
  TAMANHO.DispositivoRam_t;
POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_QUANTIDADE_FILTRO =
  POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_NOME_DISPOSTIVO +
  CONFIG.NR_NOME_DISPOSITIVO;
POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_POSICAO_DISPOSITIVO =
  POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_QUANTIDADE_FILTRO + 1;
POSICAO.TAMANHO_MENSAGEM_DISPOSITIVOS_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_DISPOSITIVOS_CENTRAIS_POSICAO_DISPOSITIVO + 1;

//DispositivoRam_t
POSICAO.POSICAO_DISPOSITIVO_RAM_BLOQUEADO = 1;
POSICAO.POSICAO_DISPOSITIVO_RAM_ENDERECO = 5;
POSICAO.POSICAO_DISPOSITIVO_RAM_BLOQUEADO_BIT = 7;
POSICAO.POSICAO_DISPOSITIVO_RAM_ATIVO_BIT_1 = 0;
POSICAO.POSICAO_DISPOSITIVO_RAM_ATIVO_BIT_2 = 1;

//CRC REGRAS TEMPORIZANDO
TAMANHO.TAMANHO_MENSAGEM_REGRAS_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_REGRAS_CENTRAIS_QUANTIDADE_REGRAS + 1;
POSICAO.POSICAO_MENSAGEM_CRC_REGRAS_CENTRAIS_CRC_REGRAS =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
TAMANHO.TAMANHO_MENSAGEM_CRC_REGRAS_CENTRAIS =
  POSICAO.POSICAO_MENSAGEM_CRC_REGRAS_CENTRAIS_CRC_REGRAS + 2;

//Lacos
POSICAO.POSICAO_LACO_1 = 1;
POSICAO.POSICAO_LACO_2 = 3;

//Informações da central
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_DISPOSITIVOS_LACO =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_SAIDAS_LACO =
  POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_DISPOSITIVOS_LACO +
  CONFIG.NR_LACOS;
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_SIRENES_LACO =
  POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_SAIDAS_LACO +
  CONFIG.NR_LACOS;
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_REGRAS =
  POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_SIRENES_LACO +
  CONFIG.NR_LACOS;
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_ZONAS =
  POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_REGRAS + 1;
POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL =
  POSICAO.POSICAO_MENSAGEM_INFORMACOES_CENTRAL_NUMERO_ZONAS + 1;

//Data e hora
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_DIA =
  POSICAO.POSICAO_MENSAGEM_COMANDO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_MES =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_DIA + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_ANO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_MES + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_HORA =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_ANO + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_MINUTO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_HORA + 1;
POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_SEGUNDO =
  POSICAO.POSICAO_MENSAGEM_INTERLIGACAO_SINCRONIZACAO_DATA_HORA_RTC_MINUTO + 1;

//RESPOSTA COMANDO BOTÃO
RESPOSTA.COMANDO_BOTAO = {
  0: "StatusBotaoOk",
  1: "StatusBotaoWaiting",
  2: "StatusBotaoNaoConfigurado",
  3: "StatusBotaoTempoRegraEstourado",
  4: "StatusBotaoTempoMultiplasRegrasEstourado",
};

CONFIG.ERRORS = {
  FAIL_DECRYPT: 1,
  FAIL_COUNTER: 2,
};

module.exports = CONFIG;
